### PR TITLE
Update RPGBot.js

### PR DESCRIPTION
**Pull request by SyregID**
**I'm fixing in the RPGBot.js**

 - [x] Bug Fixing
-  [x] Rename & Move to process.env

### CODE REVIEW

**Comment by PeachyTree** [comment]
Thanks, I just now noticed that I forgot to put `process.env` in it.

**Comment by SyregID** [comment]
You're welcome

**Comment by AzuraApple** [comment]
Hey @SyregID, by any chance if you read this, can you send me a friend request on Discord if you'd like? I'd like to talk to you, my username is AzuraApple#0955

**Comment by SyregID** [comment]
Hey, Sure add me.
My discord username is syreg#8143

Also your discord username is like invalid.

**Comment by SyregID** [comment]
image
@AzuraApple

**Comment by AzuraApple** [comment]
Whoops sorry, I misspelled it, it's actually Azura Apple#0955
I can't add you though, try to add me now ^^;

**Comment by SyregID** [comment]
Okay, got it already added.

>

**Pull request closed without merging**
